Repository RoboJackets/apiary, pull requests merged in 2018-09, with the labels that each got.

#393 Laravel 5.5 Shift
  app/Attendance.php
  app/Console/Kernel.php
  app/DuesPackage.php
  app/DuesTransaction.php
  app/Event.php
  app/Exceptions/Handler.php
  app/Http/Controllers/AttendanceController.php
  app/Http/Controllers/DuesTransactionController.php
  app/Http/Controllers/EventController.php
  app/Http/Controllers/NotificationController.php
  app/Http/Controllers/PaymentController.php
  app/Http/Controllers/RoleController.php
  app/Http/Controllers/RsvpController.php
  app/Http/Controllers/UserController.php
  app/Http/Kernel.php
  app/Http/Middleware/CASAuthenticate.php
  app/Http/Middleware/CASCheck.php
  app/Http/Middleware/EncryptCookies.php
  app/Http/Middleware/TrimStrings.php
  app/Http/Middleware/TrustProxies.php
  app/Http/Middleware/VerifyCsrfToken.php
  app/Payment.php
  app/Rsvp.php
  app/Team.php
  app/Traits/CreateOrUpdateCASUser.php
  artisan
  bootstrap/autoload.php
  composer.json
  composer.lock
  config/app.php
  config/broadcasting.php
  config/cache.php
  config/database.php
  config/filesystems.php
  config/jwt.php
  config/queue.php
  phpunit.xml
  public/.htaccess
  public/index.php
Labels: area / backend, status / code review, type / technical debt

#425 Initial Nova configuration for user management
  .gitignore
  app/Nova/Filters/UserType.php
  app/Nova/Resource.php
  app/Nova/User.php
  app/Providers/NovaServiceProvider.php
  composer.json
  composer.lock
  config/app.php
  config/nova.php
  post-deploy-hook.sh
Labels: area / frontend, priority / medium, type / feature

#452 Fix #440 (dashboard error)
  app/Http/Controllers/DashboardController.php
Labels: area / frontend, priority / critical, type / bug

#453 Create navbar dropdown menu for logout/profile
  resources/views/layouts/app.blade.php
Labels: area / frontend, priority / low, type / enhancement

#411 Fix attendance duplication
  app/Http/Controllers/AttendanceController.php
Labels: area / API, priority / medium, status / code review, type / bug

#463 Teams in Nova
  app/Nova/Team.php
  app/Nova/User.php
  app/Team.php
Labels: area / nova, priority / low, status / code review, type / feature

#436 Add RCR Controller Methods
  app/Http/Controllers/RecruitingCampaignRecipientController.php
  app/RecruitingCampaignRecipient.php
  routes/api.php
Labels: area / API, priority / low, status / pending changes, type / enhancement

#467 Add name to nova/logout route
  routes/web.php
Labels: area / nova, priority / high, type / bug

#468 Teams Tweaks
  resources/assets/js/components/attendance/AttendanceKiosk.vue
  resources/assets/js/components/attendance/AttendanceManualAdd.vue
  resources/assets/js/components/teams/TeamEditForm.vue
Labels: area / frontend, priority / medium, status / in progress, type / enhancement

#465 Switch to Horizon for queuing
  README.md
  app/Console/Kernel.php
  app/Providers/AppServiceProvider.php
  composer.json
  composer.lock
  config/horizon.php
  public/vendor/horizon/css/app.css
  public/vendor/horizon/css/app.css.map
  public/vendor/horizon/img/favicon.png
  public/vendor/horizon/img/horizon.svg
  public/vendor/horizon/img/sprite.svg
  public/vendor/horizon/js/app.js
  public/vendor/horizon/js/app.js.map
  public/vendor/horizon/mix-manifest.json
Labels: area / devOps, priority / low, status / in progress, type / feature
