Repository RoboJackets/apiary, pull requests merged in 2018-05, with the labels that each got.

#323 Add Form Validation Feedback
  resources/assets/js/components/UserEditForm.vue
  resources/assets/js/components/dues/DuesAdditionalInfo.vue
  resources/assets/js/components/dues/DuesRequiredInfo.vue
  resources/assets/js/components/events/EventCreateForm.vue
  resources/assets/js/components/events/EventEditForm.vue
Labels: area / frontend, priority / medium, status / ready to merge

#325 Add Cost field to Event Edit Form
  resources/assets/js/components/events/EventEditForm.vue
Labels: area / frontend, priority / medium, status / ready to merge, type / bug

#327 Fix minor bootstrap display error on Dues Transaction Detail
  resources/assets/js/components/dues/DuesTransaction.vue
Labels: area / frontend, priority / low, status / ready to merge, type / bug

#318 Update Dependencies
  package-lock.json
  package.json
Labels: area / devOps, priority / low, status / ready to merge

#328 Update Readme
  .env.example
  CONTRIBUTING.md
  README.md
Labels: area / devOps, priority / medium, status / code review, type / documentation

#350 Cleaning out apidocjs generation
  .circleci/config.yml
  apidoc.footer.md
  apidoc.json
Labels: area / devOps, priority / low, type / enhancement

#351 Style checker configuration changes
  .styleci.yml
Labels: area / devOps, priority / medium, type / philosophy

#356 Show payments info on Dues Transaction Page
  resources/assets/js/app.js
  resources/assets/js/components/AcceptPayment.vue
  resources/assets/js/components/dues/DuesTransaction.vue
  resources/assets/js/components/payments/ShowPayments.vue
Labels: area / frontend, priority / medium, status / code review, type / feature

#360 Clickable table rows (updated)
  resources/assets/js/components/Datatable.vue
  resources/assets/js/components/wrappers/DuesAdminTable.vue
  resources/assets/js/components/wrappers/EventsAdminTable.vue
  resources/assets/js/components/wrappers/FasetAdminTable.vue
  resources/assets/js/components/wrappers/PendingDuesTable.vue
  resources/assets/js/components/wrappers/SwagTable.vue
  resources/assets/js/components/wrappers/UsersAdminTable.vue
Labels: status / ready to merge

#361 Capture timestamp client side for FASET form
  public/js/faset/vue.js
Labels: status / ready to merge

#367 Added privacy policy
  resources/views/layouts/footer.blade.php
  resources/views/privacy.blade.php
  routes/web.php
Labels: area / frontend, priority / medium, type / documentation

#369 Preferred name defaults to legal name on user edit form
  app/User.php
  resources/assets/js/components/UserEditForm.vue
Labels: area / backend, priority / low, type / enhancement
