Repository RoboJackets/apiary, pull requests merged in 2018-10, with the labels that each got.

#484 Restrict payment methods
  app/Http/Controllers/PaymentController.php
  database/migrations/2018_09_30_161300_add_payment_method_permission.php
  resources/assets/js/components/AcceptPayment.vue
  resources/assets/js/components/dues/DuesTransaction.vue
  resources/views/dues/duestransaction.blade.php
  routes/web.php
Labels: area / frontend, priority / low, type / enhancement

#469 Dues flow back button
  app/Http/Controllers/DashboardController.php
  app/Http/Controllers/DuesTransactionController.php
  app/Http/Controllers/PaymentController.php
  resources/assets/js/components/dues/Demographics.vue
  resources/assets/js/components/dues/DuesAdditionalInfo.vue
  resources/assets/js/components/dues/DuesSequence.vue
  resources/assets/js/components/dues/SafetyAgreement.vue
Labels: area / frontend, priority / high, status / in progress, type / enhancement

#466 Remove is_admin flag
  app/Http/Controllers/DuesTransactionController.php
  app/Providers/AuthServiceProvider.php
  config/app.php
  database/migrations/2018_09_30_140630_drop_trivial_authorization.php
  database/migrations/2018_10_01_144406_add_dues_transactions_own_permission.php
  swagger.yaml
Labels: area / backend, priority / low, status / pending changes, type / technical debt

#471 Add team joining to the dues flow
  resources/assets/js/app.js
  resources/assets/js/components/dues/Demographics.vue
  resources/assets/js/components/dues/DuesSequence.vue
  resources/assets/js/components/teams/TeamCard.vue
  resources/assets/js/components/teams/TeamMembershipButton.vue
  resources/views/dues/payDues.blade.php
  resources/views/teams/index.blade.php
Labels: area / frontend, priority / high, status / in progress, type / enhancement

#482 Restrict dues flow to inactive members
  resources/views/dues/alreadypaid.blade.php
  routes/web.php
Labels: area / backend, priority / medium, type / feature

#486 More retries and fixed sleep for Square API
  app/Http/Controllers/PaymentController.php
Labels: area / backend, priority / critical, status / code review, type / bug

#488 Nova Tweaks
  app/Nova/DuesPackage.php
  app/Nova/NotificationTemplate.php
  app/Providers/NovaServiceProvider.php
  resources/assets/css/nova.css
Labels: area / nova, priority / low, type / enhancement

#493 Add security disclosure note to README
  README.md
Labels: priority / low, status / code review, type / documentation

#496 Sync OrgSync teams on login
  .env.example
  app/Traits/CreateOrUpdateCASUser.php
  config/cas.php
Labels: area / backend, priority / high, type / feature

#502 Add active members metric
  app/Nova/Metrics/ActiveMembers.php
  app/Nova/Metrics/TotalTeamMembers.php
  app/Nova/Team.php
  app/Providers/NovaServiceProvider.php
Labels: area / nova, priority / low, type / feature

#506 Fix is_active attribute
  app/User.php
Labels: type / bug

#512 Add "fast-read" kiosk checkbox
  resources/assets/js/components/attendance/AttendanceKiosk.vue
Labels: area / frontend, priority / medium, type / enhancement

#511 Add reports
  app/Nova/Actions/ExportGtid.php
  app/Nova/Actions/ExportUsername.php
  app/Nova/Actions/ResetApiToken.php
  app/Nova/Attendance.php
  app/Nova/DuesPackage.php
  app/Nova/Event.php
  app/Nova/Filters/Attendable.php
  app/Nova/Filters/DateFrom.php
  app/Nova/Filters/DateTo.php
  app/Nova/Filters/UserActiveAttendance.php
  app/Nova/Lenses/RecentInactiveUsers.php
  app/Nova/Metrics/ActiveAttendanceBreakdown.php
  app/Nova/Metrics/AttendancePerWeek.php
  app/Nova/Metrics/MemberSince.php
  app/Nova/Metrics/PaymentMethodBreakdown.php
  app/Nova/Metrics/PrimaryTeam.php
  app/Nova/Metrics/RsvpSourceBreakdown.php
  app/Nova/Metrics/SwagPickupRate.php
  app/Nova/Metrics/TotalAttendance.php
  app/Nova/Metrics/TotalCollections.php
  app/Nova/Team.php
  app/Nova/User.php
  app/Providers/NovaServiceProvider.php
  composer.json
  composer.lock
  config/app.php
  resources/assets/js/components/AcceptPayment.vue
Labels: area / nova

#525 Tweak to phrasing for no data on primary team
  app/Nova/Metrics/PrimaryTeam.php
Labels: area / nova, type / enhancement

#528 Reports tweaks
  app/Nova/Lenses/RecentInactiveUsers.php
  app/Nova/Metrics/AttendancePerWeek.php
  app/Nova/Metrics/PaymentMethodBreakdown.php
  app/Nova/Metrics/RsvpSourceBreakdown.php
Labels: area / nova

#530 Rename recent attendees metric
  app/Nova/Metrics/ActiveAttendanceBreakdown.php
Labels: area / nova, priority / medium, type / enhancement

#533 Add names to the ExportGtid action
  app/Nova/Actions/ExportGtid.php
Labels: area / nova
