Repository RoboJackets/apiary, pull requests merged in 2019-11, with the labels that each got.

#816 Laravel 6.0 Shift
  app/Http/Kernel.php
  composer.json
  composer.lock
  config/broadcasting.php
  config/cache.php
  config/database.php
  config/filesystems.php
  config/mail.php
  config/queue.php
  config/services.php
  phpunit.xml
Labels: area / backend, priority / medium, type / technical debt

#943 Miscellaneous Nova cards and other tweaks
  .github/workflows/auto-approve-renovate.yml
  .github/workflows/ci.yml
  .mergify.yml
  app/Http/Controllers/AttendanceController.php
  app/Jobs/NoAttendanceJediPush.php
  app/Nova/Attendance.php
  app/Nova/Dashboards/JEDI.php
  app/Nova/DuesTransaction.php
  app/Nova/Metrics/AccessOverrides.php
  app/Nova/Metrics/AttendanceSourceBreakdown.php
  app/Nova/Metrics/FieldByActiveBreakdown.php
  app/Nova/Metrics/LinkedGitHubAccounts.php
  app/Nova/Metrics/LinkedGoogleAccounts.php
  app/Nova/Metrics/PendingGitHubInvitations.php
  app/Nova/Metrics/ResumesSubmitted.php
  app/Nova/Metrics/SUMSUsers.php
  app/Nova/User.php
  app/Providers/NovaServiceProvider.php
  app/User.php
  phpstan.neon
  public/img/contactless-24px.svg
  public/img/contactless-card-24px.svg
  resources/js/components/attendance/AttendanceKiosk.vue
  resources/sass/user.scss
Labels: area / frontend, area / nova, priority / low, type / enhancement, type / feature

#965 Add waiver payment method
  app/Http/Requests/StorePaymentRequest.php
  app/Notifications/Dues/SummaryNotification.php
  app/Nova/Actions/AddPayment.php
  app/Nova/Metrics/PaymentMethodBreakdown.php
  app/Nova/Payment.php
  app/Payment.php
  database/migrations/2019_11_17_141409_add_waiver_payment_method_permission.php
  phpcs.xml
Labels: area / backend, priority / critical, type / enhancement

#966 Fix attendance export
  app/Attendance.php
  app/Http/Controllers/AttendanceReportController.php
  app/Nova/Actions/ExportAttendance.php
  phpstan.neon
  routes/api.php
Labels: area / backend, priority / critical, type / bug

#977 Add attendance as includable relationship on User Resources
  app/Http/Resources/User.php
Labels: area / API, priority / low, type / enhancement
