Repository RoboJackets/apiary, pull requests merged in 2019-04, with the labels that each got.

#597 Add Support for Contactless Kiosk Attendance
  app/Http/Resources/Permission.php
  app/Http/Resources/Role.php
  app/Http/Resources/User.php
  app/User.php
  database/migrations/2019_03_24_194754_role_permission_permissions.php
  public/img/nfc-logo.svg
  resources/assets/js/components/attendance/AttendanceKiosk.vue
Labels: status / in progress

#605 Create Nova "Hidden" field type for GTIDs and API keys
  app/Nova/Fields/Hidden.php
  app/Nova/User.php
  resources/assets/js/components/nova/HiddenFieldDetail.vue
  resources/assets/js/nova.js
Labels: area / nova, type / enhancement

#606 Only compare attendable and GTID when deduplicating attendance
  app/Http/Controllers/AttendanceController.php
Labels: area / API, priority / medium, type / bug
