Repository RoboJackets/apiary, pull requests merged in 2020-01, with the labels that each got.

#1032 Fix DuesTransactions in Nova
  app/Nova/Attendance.php
  app/Nova/DuesTransaction.php
  app/Nova/Filters/DuesTransactionPaymentStatus.php
  app/Nova/Filters/DuesTransactionSwagStatus.php
  phpstan.neon
Labels: area / nova, priority / critical, type / regression

#1055 Revert bad type hint
  app/Nova/Filters/DuesTransactionTeam.php
  app/Nova/Team.php
Labels: area / nova, priority / medium, type / bug

#1061 Add ClickUp fields to users
  .editorconfig
  app/Http/Controllers/ClickUpController.php
  app/Http/Controllers/UserController.php
  app/Http/Requests/UpdateUserRequest.php
  app/Http/Resources/User.php
  app/Jobs/PushToJedi.php
  app/Nova/User.php
  database/migrations/2020_01_12_160642_add_clickup_fields_to_users.php
  resources/js/components/UserEditForm.vue
  resources/views/clickup.blade.php
  routes/web.php
Labels: area / jedi, priority / critical, type / feature

#1062 Clarify save message if clickup email was changed
  resources/js/components/UserEditForm.vue
Labels: area / jedi, priority / medium, type / enhancement

#1064 Add preliminary support for multiple Google accounts
  app/Jobs/PushToJedi.php
Labels: area / jedi, priority / low, type / feature

#1066 Minor updates to CodeSniffer
  app/Nova/User.php
  app/Providers/NovaServiceProvider.php
  phpcs.xml
Labels: area / devOps, priority / low, type / technical debt

#1076 Accept more than 6 teams on the kiosk
  public/img/nfc-logo.svg
  resources/js/components/attendance/AttendanceKiosk.vue
Labels: area / frontend, priority / low, type / enhancement

#1081 Fix #1077
  app/Http/Controllers/UserController.php
  app/Http/Requests/UpdateUserRequest.php
Labels: area / API, priority / high, type / bug

#1084 Fix multiple bugs
  app/Event.php
  app/Http/Requests/StoreUserRequest.php
  app/Http/Requests/UpdateUserRequest.php
  app/User.php
Labels: area / backend, area / frontend, area / nova, priority / high, type / bug
