Repository RoboJackets/apiary, pull requests merged in 2020-09, with the labels that each got.

#1332 Add Bugsnag JavaScript integration
  app/Jobs/DuesPackageSync.php
  package-lock.json
  package.json
  resources/js/app.js
  resources/js/components/attendance/AttendanceExport.vue
  resources/js/components/attendance/AttendanceManualAdd.vue
  resources/views/layouts/head.blade.php
Labels: area / devOps, priority / medium, type / feature

#1368 Remove Google Analytics
  .env.example
  config/app.php
  resources/views/layouts/head.blade.php
Labels: area / frontend, priority / high, type / technical debt

#1367 Update privacy policy, Add GDPR information.
  resources/views/privacy.blade.php
Labels: area / frontend, status / code review, type / documentation
