Repository RoboJackets/apiary, pull requests merged in 2021-07, with the labels that each got.

#1836 Disable phpunit process isolation
  phpunit.xml
Labels: area / devOps, priority / low, type / technical debt

#1853 Add Laravel Scout
  .env.testing
  .phan/config.php
  app/Models/Attendance.php
  app/Models/DuesTransaction.php
  app/Models/Event.php
  app/Models/Team.php
  app/Models/Travel.php
  app/Models/TravelAssignment.php
  app/Models/User.php
  app/Nova/Attendance.php
  app/Nova/AttendanceExport.php
  app/Nova/ClassStanding.php
  app/Nova/DuesPackage.php
  app/Nova/DuesTransaction.php
  app/Nova/Event.php
  app/Nova/Major.php
  app/Nova/Merchandise.php
  app/Nova/NotificationTemplate.php
  app/Nova/OAuth2AccessToken.php
  app/Nova/OAuth2Client.php
  app/Nova/Payment.php
  app/Nova/RecruitingVisit.php
  app/Nova/RemoteAttendanceLink.php
  app/Nova/Resource.php
  app/Nova/Rsvp.php
  app/Nova/Team.php
  app/Nova/Travel.php
  app/Nova/TravelAssignment.php
  app/Nova/User.php
  app/Observers/AttendanceObserver.php
  app/Observers/PaymentObserver.php
  app/Observers/SignatureObserver.php
  composer.json
  composer.lock
  config/healthcheck.php
  post-deploy-hook.sh
Labels: area / nova, priority / high, type / feature

#1868 Tweak dues packages in Nova
  app/Nova/DuesPackage.php
Labels: area / nova, priority / high, type / bug

#1869 Subtract processing fees from total for dues summary notification
  app/Notifications/Dues/SummaryNotification.php
Labels: area / backend, priority / low, type / bug

#1870 Swap out Bugsnag for Sentry
  .env.example
  .phan/config.php
  app/Console/Kernel.php
  app/Exceptions/Handler.php
  app/Http/Controllers/AttendanceController.php
  app/Http/Controllers/DuesPackageController.php
  app/Http/Controllers/DuesTransactionController.php
  app/Http/Controllers/EventController.php
  app/Http/Controllers/PaymentController.php
  app/Http/Controllers/PermissionController.php
  app/Http/Controllers/RecruitingCampaignController.php
  app/Http/Controllers/RecruitingVisitController.php
  app/Http/Controllers/RoleController.php
  app/Http/Controllers/RsvpController.php
  app/Http/Controllers/TeamController.php
  app/Http/Controllers/UserController.php
  app/Providers/AppServiceProvider.php
  composer.json
  composer.lock
  config/app.php
  config/bugsnag.php
  config/logging.php
  config/sentry.php
  package-lock.json
  package.json
  phpstan.neon
  post-deploy-hook.sh
  resources/js/app.js
  resources/views/layouts/head.blade.php
Labels: area / devOps, priority / medium, type / technical debt
