Repository RoboJackets/apiary, pull requests merged in 2021-01, with the labels that each got.

#1530 Clean up duplicated code in Nova
  app/Http/Requests/StoreUserRequest.php
  app/Http/Requests/UpdateUserRequest.php
  app/Models/Team.php
  app/Models/User.php
  app/Nova/Attendance.php
  app/Nova/AttendanceExport.php
  app/Nova/ClassStanding.php
  app/Nova/DuesPackage.php
  app/Nova/DuesTransaction.php
  app/Nova/Event.php
  app/Nova/Major.php
  app/Nova/Metrics/ShirtSizeBreakdown.php
  app/Nova/NotificationTemplate.php
  app/Nova/Payment.php
  app/Nova/RecruitingVisit.php
  app/Nova/Resource.php
  app/Nova/Rsvp.php
  app/Nova/Team.php
  app/Nova/User.php
Labels: area / nova, priority / low, type / technical debt

#1531 Membership agreements
  app/Http/Controllers/DashboardController.php
  app/Http/Controllers/DuesTransactionController.php
  app/Http/Controllers/SUMSController.php
  app/Http/Controllers/SignatureController.php
  app/Http/Controllers/SquareCheckoutController.php
  app/Http/Requests/MembershipAgreementCompleteRequest.php
  app/Http/Requests/MembershipAgreementRedirectRequest.php
  app/Http/Requests/StoreUserRequest.php
  app/Http/Requests/UpdateUserRequest.php
  app/Http/Resources/User.php
  app/Jobs/PushToJedi.php
  app/Jobs/RetrieveIpAddressGeoLocationForSignature.php
  app/Mail/MembershipAgreementSigned.php
  app/Models/MembershipAgreementTemplate.php
  app/Models/Signature.php
  app/Models/User.php
  app/Notifications/MembershipAgreementSigned.php
  app/Nova/Actions/OverrideAccess.php
  app/Nova/DuesTransaction.php
  app/Nova/MembershipAgreementTemplate.php
  app/Nova/Payment.php
  app/Nova/Signature.php
  app/Nova/User.php
  app/Observers/MembershipAgreementTemplateObserver.php
  app/Observers/SignatureObserver.php
  app/Policies/MembershipAgreementTemplatePolicy.php
  app/Policies/SignaturePolicy.php
  app/Providers/AppServiceProvider.php
  composer.json
  composer.lock
  config/dompdf.php
  config/horizon.php
  config/ipstack.php
  config/services.php
  config/sums.php
  database/factories/UserFactory.php
  database/migrations/2021_01_01_130254_create_membership_agreement_templates_table.php
  database/migrations/2021_01_01_131555_create_signatures_table.php
  database/migrations/2021_01_01_150634_add_membership_agreement_permissions.php
  database/migrations/2021_01_02_142913_drop_safety_agreement_column.php
  phpstan.neon
  resources/views/agreement/alreadysigned.blade.php
  resources/views/agreement/error.blade.php
  resources/views/agreement/print.blade.php
  resources/views/agreement/render.blade.php
  resources/views/dues/agreementrequired.blade.php
  resources/views/dues/flow.blade.php
  resources/views/mail/agreement/signed.blade.php
  resources/views/welcome.blade.php
  routes/web.php
  storage/app/.gitignore
  storage/app/dompdf/.gitignore
Labels: area / backend, priority / critical, type / feature

#1424 Remote attendance links version 2
  .gitignore
  app/Http/Controllers/RemoteAttendanceController.php
  app/Http/Resources/Attendance.php
  app/Models/Attendance.php
  app/Models/Event.php
  app/Models/RemoteAttendanceLink.php
  app/Models/Team.php
  app/Nova/Actions/CreateRemoteAttendanceLink.php
  app/Nova/Actions/ResetRemoteAttendance.php
  app/Nova/Attendance.php
  app/Nova/Event.php
  app/Nova/Metrics/AttendanceSourceBreakdown.php
  app/Nova/RemoteAttendanceLink.php
  app/Nova/Team.php
  app/Policies/RemoteAttendanceLinkPolicy.php
  app/Providers/AuthServiceProvider.php
  composer.json
  composer.lock
  database/migrations/2020_10_08_161930_create_remote_attendance_links_table.php
  database/migrations/2020_10_14_131630_remove_remote_attendance_fields_from_teams_table.php
  database/migrations/2020_10_15_141336_add_remote_attendance_links_permissions.php
  database/migrations/2021_01_06_210602_add_remote_attendance_link_id_column_to_attendance_table.php
  resources/views/attendance/remote.blade.php
  routes/web.php
Labels: area / backend, area / database, area / frontend, area / nova, priority / high, type / feature

#1552 Improved membership agreement rendering
  app/Http/Controllers/SignatureController.php
  app/Http/Requests/MembershipAgreementRedirectRequest.php
  app/Mail/MembershipAgreementSigned.php
  app/Models/MembershipAgreementTemplate.php
  app/Nova/MembershipAgreementTemplate.php
  resources/views/agreement/print.blade.php
  resources/views/agreement/render.blade.php
Labels: area / backend, priority / critical, type / enhancement

#1564 Support MS Teams in RAL user facing action
  app/Nova/Actions/CreateRemoteAttendanceLink.php
  app/Nova/RemoteAttendanceLink.php
Labels: area / nova, priority / low, type / feature

#1568 Membership agreement print rendering improvements
  app/Http/Controllers/SignatureController.php
  config/dompdf.php
  resources/views/agreement/print.blade.php
Labels: area / backend, priority / critical, type / enhancement

#1570 Add Nova action to reset idempotency key and clean up other actions
  app/Http/Controllers/SquareCheckoutController.php
  app/Models/Payment.php
  app/Nova/Actions/AddPayment.php
  app/Nova/Actions/CreateDuesPackages.php
  app/Nova/Actions/DistributePolo.php
  app/Nova/Actions/DistributeShirt.php
  app/Nova/Actions/OverrideAccess.php
  app/Nova/Actions/RefreshFromGTED.php
  app/Nova/Actions/ResetApiToken.php
  app/Nova/Actions/ResetIdempotencyKey.php
  app/Nova/Actions/SendRecruitingEmail.php
  app/Nova/Actions/SyncAccess.php
  app/Nova/Payment.php
  phpstan.neon
Labels: area / backend, priority / low, type / feature

#1576 Copy changes for agreement/dues cards
  resources/views/welcome.blade.php
Labels: area / frontend, priority / high, type / enhancement

#1581 Ignore payments that are not COMPLETED
  app/Jobs/ProcessSquareWebhook.php
Labels: area / backend, priority / critical, type / bug

#1582 Fix #1578
  resources/js/components/dues/DuesRequiredInfo.vue
Labels: area / frontend, priority / low, type / enhancement

#1597 Tweak payment instructions
  resources/js/components/PaymentInstructions.vue
  resources/js/components/dues/DuesSequence.vue
Labels: area / frontend, priority / low, type / enhancement

#1599 Improved validation and error handling for user edit forms
  app/Http/Requests/UpdateUserRequest.php
  resources/js/components/UserEditForm.vue
  resources/js/components/dues/DuesAdditionalInfo.vue
Labels: area / frontend, priority / high, type / bug
