Repository RoboJackets/apiary, pull requests merged in 2021-08, with the labels that each got.

#1885 Adding Graduation Date to Dues Flow
  app/Http/Resources/DuesPackage.php
  app/Nova/User.php
  package-lock.json
  resources/js/components/dues/DuesRequiredInfo.vue
  resources/js/components/fields/TermInput.vue
Labels: area / frontend, type / feature

#1887 Add Graduation Information to Profile
  app/Http/Resources/User.php
  resources/js/components/UserEditForm.vue
Labels: area / frontend, priority / medium, type / feature

#1889 Add graduation date to privacy policy
  resources/views/privacy.blade.php
Labels: area / frontend, priority / high, type / enhancement

#1891 Add API endpoints for mobile app
  app/Http/Controllers/InfoController.php
  app/Http/Controllers/UserController.php
  app/Http/Resources/User.php
  app/Models/User.php
  phpstan.neon
  routes/api.php
  tests/Feature/ApiAuthTest.php
  tests/Feature/SimpleRequestsTest.php
Labels: area / API, priority / high, type / feature

#1890 Switch payments null check to having instead of where
  app/Models/DuesPackage.php
Labels: area / database, priority / critical, type / bug

#1913 Attempt to fix stuck dues flow
  resources/js/components/dues/DuesRequiredInfo.vue
Labels: area / frontend, priority / high, type / bug

#1960 Updates for MeiliSearch v0.21.0
  app/Models/Attendance.php
  app/Models/DuesTransaction.php
  app/Models/Team.php
  app/Models/TravelAssignment.php
  app/Models/User.php
  app/Nova/Resource.php
  composer.json
  composer.lock
Labels: priority / critical, type / technical debt, area / nova
