Repository RoboJackets/apiary, pull requests merged in 2021-05, with the labels that each got.

#1737 Add resume test
  app/Http/Controllers/ResumeController.php
  phpstan.neon
  resources/test/resume-twopage.pdf
  resources/test/resume.docx
  resources/test/resume.pdf
  tests/Feature/ResumeTest.php
Labels: area / devOps, priority / low, type / technical debt

#1745 Basic travel management
  app/Http/Controllers/DashboardController.php
  app/Http/Controllers/SquareCheckoutController.php
  app/Http/Controllers/TravelAssignmentController.php
  app/Models/Signature.php
  app/Models/Travel.php
  app/Models/TravelAssignment.php
  app/Models/User.php
  app/Nova/Actions/AddPayment.php
  app/Nova/Travel.php
  app/Nova/TravelAssignment.php
  app/Nova/User.php
  app/Policies/TravelAssignmentPolicy.php
  app/Policies/TravelPolicy.php
  app/Providers/AppServiceProvider.php
  app/Providers/AuthServiceProvider.php
  database/migrations/2021_05_15_121109_create_travel_table.php
  database/migrations/2021_05_15_122154_create_travel_assignments_table.php
  database/migrations/2021_05_15_135936_add_manage_travel_permission.php
  phpstan.neon
  phpunit.xml
  resources/views/layouts/app.blade.php
  resources/views/mail/payment/confirmation.blade.php
  resources/views/travel/actionrequired.blade.php
  resources/views/travel/index.blade.php
  resources/views/travel/noassignment.blade.php
  resources/views/welcome.blade.php
  routes/web.php
Labels: priority / high, type / feature

#1771 Upgrade apereo/phpcas to 1.3.9
  composer.json
  composer.lock
Labels: area / devOps, priority / low, type / technical debt

#1772 Use dynamic CAS hostname for login button
  resources/views/layouts/app.blade.php
Labels: area / frontend, priority / low, type / bug
