Repository RoboJackets/apiary, pull requests merged in 2021-09, with the labels that each got.

#1967 Make Provided By on merch pivot a BelongsTo
  app/Models/DuesTransaction.php
  app/Models/DuesTransactionMerchandise.php
  app/Models/Merchandise.php
  app/Models/User.php
  app/Nova/DuesTransaction.php
  app/Nova/Merchandise.php
  app/Nova/MerchandisePivotFields.php
  app/Nova/Payment.php
  phpstan.neon
Labels: priority / low, type / technical debt, area / nova

#2006 Fix #2005
  .env.testing
  app/Models/MembershipAgreementTemplate.php
  app/Notifications/MembershipAgreementSigned.php
  database/factories/MembershipAgreementTemplateFactory.php
  database/seeders/MembershipAgreementTemplateSeeder.php
  tests/Feature/SignatureTest.php
  tests/TestCase.php
Labels: area / backend, priority / high, type / bug

#2023 Demo mode for Google Play review
  app/Http/Controllers/BuzzApiMockController.php
  app/Http/Middleware/CASAuthenticate.php
  app/Http/Middleware/VerifyCsrfToken.php
  app/Nova/Metrics/TransactionsByDuesPackage.php
  app/Traits/CreateOrUpdateCASUser.php
  config/features.php
  config/healthcheck.php
  routes/web.php
Labels: priority / critical, type / feature, area / devOps

#2036 Update .env.example to be more useful
  .env.example
Labels: priority / low, type / documentation, area / devOps

#2044 Remove dependency on gtAccountEntitlement from CAS
  app/Traits/CreateOrUpdateCASUser.php
  composer.lock
Labels: priority / critical, type / enhancement, area / devOps
