Repository RoboJackets/apiary, pull requests merged in 2022-06, with the labels that each got.

#2565 New dues payment reminder email
  app/Http/Controllers/DuesTransactionController.php
  app/Http/Controllers/SquareCheckoutController.php
  app/Jobs/SendDuesPaymentReminder.php
  app/Mail/Dues/RequestComplete.php
  app/Mail/DuesPaymentReminder.php
  app/Models/Payment.php
  app/Models/User.php
  app/Notifications/Dues/RequestCompleteNotification.php
  app/Notifications/DuesPaymentReminder.php
  app/Observers/DuesTransactionObserver.php
  app/Observers/PaymentObserver.php
  composer.json
  composer.lock
  config/htmlmin.php
  phpstan.neon
  phpunit.xml
  resources/views/mail/database.blade.php
  resources/views/mail/dues/requestcomplete.blade.php
  resources/views/mail/duespaymentreminder.blade.php
  tests/Feature/DuesPaymentReminderJobTest.php
  tests/Unit/DuesPaymentReminderEmailTest.php
Labels: priority / high, type / enhancement, area / email

#2578 Add user impersonation
  app/Http/Controllers/AuthController.php
  app/Models/User.php
  app/Providers/NovaServiceProvider.php
  database/migrations/2022_06_04_104801_add_impersonate_users_permission.php
  resources/views/layouts/app.blade.php
  routes/web.php
  tests/Feature/PermissionsAndRolesTest.php
Labels: priority / medium, type / feature, area / nova

#2582 New payment receipt email
  app/Http/Controllers/PaymentController.php
  app/Jobs/ProcessSquareWebhook.php
  app/Mail/Payment/Confirmation.php
  app/Mail/PaymentReceipt.php
  app/Models/Travel.php
  app/Models/TravelAssignment.php
  app/Notifications/DuesPaymentReminder.php
  app/Notifications/PaymentReceipt.php
  app/Nova/Actions/AddPayment.php
  app/Nova/Travel.php
  database/factories/TravelAssignmentFactory.php
  database/factories/TravelFactory.php
  resources/views/mail/payment/confirmation.blade.php
  resources/views/mail/paymentreceipt.blade.php
  tests/Unit/PaymentReceiptEmailTest.php
Labels: priority / high, type / enhancement, area / email

#2584 Switch remaining emails to plain text
  app/Mail/DuesPaymentReminder.php
  app/Mail/ExpiringPersonalAccessToken.php
  app/Mail/MembershipAgreementSigned.php
  app/Models/Signature.php
  app/Notifications/ExpiringPersonalAccessTokenNotification.php
  app/Notifications/MembershipAgreementSigned.php
  database/factories/SignatureFactory.php
  phpstan.neon
  resources/views/mail/agreement/signed.blade.php
  resources/views/mail/oauth2/pat_expiration.blade.php
  tests/Unit/ExpiringPersonalAccessTokenEmailTest.php
  tests/Unit/MembershipAgreementSignedEmailTest.php
Labels: priority / high, type / enhancement, area / email

#2585 Add unsubscribe links to emails and handle events from Postmark
  app/Jobs/ProcessPostmarkOutboundWebhook.php
  app/Jobs/SendDuesPaymentReminder.php
  app/Jobs/SendExpiringPersonalAccessTokenNotifications.php
  app/Mail/DuesPaymentReminder.php
  app/Mail/ExpiringPersonalAccessToken.php
  app/Mail/MembershipAgreementSigned.php
  app/Mail/PaymentReceipt.php
  app/Models/User.php
  app/Notifications/DuesPaymentReminder.php
  app/Notifications/ExpiringPersonalAccessTokenNotification.php
  app/Notifications/MembershipAgreementSigned.php
  app/Notifications/PaymentReceipt.php
  app/Nova/User.php
  app/Observers/DuesTransactionObserver.php
  app/Observers/PaymentObserver.php
  app/SignatureValidators/PostmarkOutbound.php
  composer.json
  composer.lock
  config/webhook-client.php
  database/migrations/2022_06_05_160715_add_email_suppression_reason_to_users.php
  phpstan.neon
  resources/views/mail/agreement/signed.blade.php
  resources/views/mail/duespaymentreminder.blade.php
  resources/views/mail/oauth2/pat_expiration.blade.php
  resources/views/mail/paymentreceipt.blade.php
  routes/api.php
  tests/Feature/DuesPaymentReminderJobTest.php
  tests/Unit/DuesPaymentReminderEmailTest.php
  tests/Unit/ExpiringPersonalAccessTokenEmailTest.php
  tests/Unit/MembershipAgreementSignedEmailTest.php
  tests/Unit/PaymentReceiptEmailTest.php
Labels: priority / high, type / feature, area / email

#2588 Tweak welcome language on home page
  app/Http/Controllers/DashboardController.php
  resources/js/components/dues/SelfServiceAccessOverride.vue
  resources/views/welcome.blade.php
Labels: area / frontend, priority / medium, type / enhancement

#2591 Add null check for dues payment reminder
  app/Jobs/SendDuesPaymentReminder.php
  app/Notifications/DuesPaymentReminder.php
  phpstan.neon
Labels: priority / high, type / bug, area / email

#2593 Fix Postmark outbound webhook job
  app/Jobs/ProcessPostmarkOutboundWebhook.php
  app/Models/DuesPackage.php
  app/Models/User.php
  phpstan.neon
Labels: priority / high, type / bug, area / email

#2599 Send payment receipt exactly once
  app/Http/Controllers/PaymentController.php
  app/Jobs/ProcessSquareWebhook.php
  app/Jobs/PruneDuesNotificationsInNova.php
  app/Jobs/PushToJedi.php
  app/Jobs/SendPaymentReceipt.php
  app/Nova/Actions/AddPayment.php
  app/Nova/Payment.php
  app/Observers/PaymentObserver.php
  database/migrations/2022_06_07_183212_add_receipt_sent_column_to_payments.php
  tests/Unit/UserTest.php
Labels: priority / high, type / bug, area / email

#2615 Improve DocuSign integration
  .nomad/apiary.nomad
  .nomad/conf/nginx.conf
  .nomad/var-files/google-play-review.hcl
  .nomad/var-files/production.hcl
  .nomad/var-files/test.hcl
  app/Http/Controllers/DashboardController.php
  app/Http/Controllers/DocuSignController.php
  app/Http/Controllers/TravelAssignmentController.php
  app/Jobs/ProcessPostmarkInboundWebhook.php
  app/Models/DocuSignEnvelope.php
  app/Models/TravelAssignment.php
  app/Models/User.php
  app/Nova/DocuSignEnvelope.php
  app/Nova/TravelAssignment.php
  app/Nova/User.php
  app/Observers/DocuSignEnvelopeObserver.php
  app/Policies/DocuSignEnvelopePolicy.php
  app/Policies/TravelAssignmentPolicy.php
  app/Providers/AppServiceProvider.php
  app/Providers/AuthServiceProvider.php
  app/SignatureValidators/Postmark.php
  composer.json
  composer.lock
  config/docusign.php
  config/filesystems.php
  config/webhook-client.php
  database/migrations/2022_06_10_165202_create_docusign_envelopes_table.php
  database/migrations/2022_06_11_185938_make_payload_large_text_on_webhook_calls.php
  database/migrations/2022_06_12_125310_add_view_docusign_envelopes_permission.php
  phpstan.neon
  resources/views/layouts/app.blade.php
  resources/views/travel/alreadysigned.blade.php
  resources/views/travel/index.blade.php
  resources/views/welcome.blade.php
  routes/api.php
  routes/web.php
Labels: area / backend, priority / medium, type / feature

#2616 General RAL fixes
  app/Models/RemoteAttendanceLink.php
  app/Nova/Actions/CreateRemoteAttendanceLink.php
  app/Nova/RemoteAttendanceLink.php
  tests/Unit/RemoteAttendanceLinkTest.php
Labels: priority / high, type / bug, area / nova

#2635 Add support for airfare and covid-only powerforms
  app/Jobs/ProcessPostmarkInboundWebhook.php
  app/Models/TravelAssignment.php
  app/Nova/Travel.php
  config/docusign.php
Labels: area / backend, priority / medium, type / feature

#2639 Add support for envelope view notifications
  app/Jobs/ProcessPostmarkInboundWebhook.php
  app/Models/DocuSignEnvelope.php
  app/Nova/DocuSignEnvelope.php
  database/migrations/2022_06_16_221823_add_sent_by_to_docusign_envelopes.php
  phpstan.neon
Labels: priority / low, type / enhancement, area / email

#2648 Change kiosk grid to 2 wide by 3 tall
  resources/js/components/attendance/AttendanceKiosk.vue
Labels: area / frontend, priority / low, type / enhancement

#2650 Add action to download DocuSign forms for travel
  .env.testing
  app/Nova/Actions/DownloadDocuSignForms.php
  app/Nova/Actions/ExportResumes.php
  app/Nova/Merchandise.php
  app/Nova/Travel.php
  phpstan.neon
Labels: priority / high, type / feature, area / nova

#2663 Add a custom error page for 502 errors and remap to 503
  .nomad/conf/nginx.conf
  public/maintenance-page.html
Labels: priority / low, type / enhancement, area / devOps

#2664 Enable DocuSign for membership agreements
  app/Http/Controllers/DashboardController.php
  app/Http/Controllers/DocuSignController.php
  app/Http/Controllers/DuesTransactionController.php
  app/Http/Controllers/SUMSController.php
  app/Http/Controllers/SignatureController.php
  app/Http/Controllers/SquareCheckoutController.php
  app/Http/Controllers/TravelAssignmentController.php
  app/Http/Resources/User.php
  app/Jobs/ProcessPostmarkInboundWebhook.php
  app/Jobs/PushToJedi.php
  app/Mail/MembershipAgreementDocuSignEnvelopeReceived.php
  app/Mail/MembershipAgreementSigned.php
  app/Models/Signature.php
  app/Models/User.php
  app/Notifications/MembershipAgreementDocuSignEnvelopeReceived.php
  app/Nova/Actions/OverrideAccess.php
  app/Nova/DocuSignEnvelope.php
  app/Nova/DuesTransaction.php
  app/Nova/Signature.php
  app/Nova/TravelAssignment.php
  app/Nova/User.php
  app/Observers/SignatureObserver.php
  app/Providers/AppServiceProvider.php
  config/docusign.php
  config/features.php
  phpstan.neon
  resources/views/dues/agreementrequired.blade.php
  resources/views/mail/agreement/docusignenvelopereceived.blade.php
  resources/views/mail/travel/docusignenvelopereceived.blade.php
  resources/views/welcome.blade.php
  routes/web.php
  tests/Unit/MembershipAgreementDocuSignEnvelopeReceivedEmailTest.php
  tests/Unit/TravelDocuSignEnvelopeReceivedEmailTest.php
Labels: area / backend, priority / critical, type / feature

#2666 Switch to Square Payment Link API
  app/Http/Controllers/SquareCheckoutController.php
  app/Nova/Payment.php
  composer.json
  composer.lock
  database/migrations/2022_06_26_131552_add_url_to_payments_table.php
  phpstan.neon
Labels: area / backend, priority / high, type / technical debt

#2675 Add instructions for downloading DocuSign forms to completion email
  resources/views/mail/travel/allassignmentscomplete.blade.php
  tests/Unit/AllTravelAssignmentsCompleteEmailTest.php
Labels: priority / low, type / documentation, area / email

#2678 Scrub X-Xsrf-Token and X-Csrf-Token header values in Sentry
  app/Http/Kernel.php
  app/Http/Middleware/AddUserToSentryEvents.php
  app/Http/Middleware/Sentry.php
  app/Sentry/Helpers.php
  config/sentry.php
  phpstan.neon
Labels: priority / low, type / enhancement, area / devOps
