Repository RoboJackets/apiary, pull requests merged in 2022-05, with the labels that each got.

#2359 Initial attempt at Dockerizing
  .dockerignore
  .editorconfig
  .gitignore
  .nomad/apiary.nomad
  .nomad/conf/.env.tpl
  .nomad/conf/.my.cnf
  .nomad/conf/nginx.conf
  .nomad/conf/www.conf
  .nomad/scripts/healthcheck.sh
  .nomad/scripts/prestart.sh
  .nomad/scripts/scheduler.sh
  .nomad/scripts/set-job-name.sh
  .nomad/scripts/web.sh
  .nomad/scripts/worker.sh
  .nomad/var-files/google-play-review.hcl
  .nomad/var-files/production.hcl
  .nomad/var-files/test.hcl
  Dockerfile
  README.md
  app/Http/Middleware/CASAuthenticate.php
  app/Providers/AppServiceProvider.php
  app/Providers/AuthServiceProvider.php
  app/Sentry/Helpers.php
  composer.json
  composer.lock
  config/healthcheck.php
  config/horizon.php
  config/sentry.php
  database/migrations/2022_05_07_104056_add_people_counter_id_to_attendance.php
  database/schema/mysql-schema.dump
  docker-compose.yml
  resources/js/app.js
  resources/views/layouts/head.blade.php
  storage/app/.gitignore
  storage/app/nova-exports/.gitignore
  storage/quickstart.sqlite
  webpack.mix.js
Labels: priority / medium, type / feature, area / devOps

#2466 Pre-compress static assets and add CSP header
  .nomad/conf/nginx.conf
  Dockerfile
  app/Http/ContentSecurityPolicy.php
  app/Http/Kernel.php
  app/Providers/NovaServiceProvider.php
  composer.json
  composer.lock
  config/csp.php
  resources/js/components/Datatable.vue
  resources/views/layouts/head.blade.php
Labels: priority / high, type / enhancement, area / devOps

#2486 Fix Content-Security-Policy for Firefox
  app/Http/ContentSecurityPolicy.php
Labels: area / frontend, priority / critical, type / bug

#2488 Skip pre-compressing assets for non-production images
  .nomad/apiary.nomad
  Dockerfile
  README.md
Labels: priority / low, type / enhancement, area / devOps

#2493 Add Sentry trace ID to footer
  .gitignore
  app/Models/User.php
  resources/js/components/nova/TraceId.vue
  resources/js/nova.js
  resources/views/layouts/footer.blade.php
  resources/views/vendor/nova/partials/footer.blade.php
  resources/views/vendor/nova/partials/meta.blade.php
Labels: priority / low, type / feature, area / devOps

#2494 Performance improvements
  app/Http/Kernel.php
  app/Models/User.php
  app/Providers/NovaServiceProvider.php
  composer.json
  composer.lock
  config/htmlmin.php
  database/migrations/2022_05_15_123358_add_index_to_payments_table.php
  database/migrations/2022_05_15_123930_add_indices_to_attendance_table.php
Labels: area / backend, priority / high, type / enhancement

#2496 Nova performance improvements
  .nomad/conf/www.conf
  Dockerfile
  app/Providers/NovaServiceProvider.php
Labels: area / backend, priority / medium, type / enhancement

#2499 Put back Meilisearch
  .nomad/apiary.nomad
  .nomad/conf/.env.tpl
  .nomad/scripts/prestart.sh
  app/Models/Attendance.php
  app/Models/DuesTransaction.php
  app/Models/Event.php
  app/Models/Team.php
  app/Models/Travel.php
  app/Models/TravelAssignment.php
  app/Models/User.php
  app/Observers/AttendanceObserver.php
  app/Observers/PaymentObserver.php
  app/Observers/SignatureObserver.php
  composer.json
  composer.lock
Labels: area / backend, priority / high, type / technical debt

#2508 Remove vestigal fields
  app/Http/Controllers/DashboardController.php
  app/Http/Controllers/TravelAssignmentController.php
  app/Http/Requests/StoreEventRequest.php
  app/Http/Requests/UpdateEventRequest.php
  app/Http/Resources/Event.php
  app/Models/Event.php
  app/Models/Travel.php
  app/Models/TravelAssignment.php
  app/Nova/Event.php
  app/Nova/Metrics/DocumentsReceivedForTravel.php
  app/Nova/Travel.php
  app/Nova/TravelAssignment.php
  app/Providers/NovaServiceProvider.php
  database/migrations/2022_05_20_231319_drop_cost_from_events.php
  database/migrations/2022_05_20_232218_drop_docs_required_from_travel.php
  resources/views/rsvp/confirmation.blade.php
  resources/views/travel/index.blade.php
  resources/views/welcome.blade.php
Labels: area / database, priority / low, type / technical debt

#2526 Fix form-action directive to allow membership agreement redirects
  app/Http/ContentSecurityPolicy.php
Labels: area / frontend, priority / critical, type / regression

#2547 Delete recruiting
  app/Console/Kernel.php
  app/Http/Controllers/AttendanceExportController.php
  app/Http/Controllers/NotificationController.php
  app/Http/Controllers/NotificationTemplateController.php
  app/Http/Controllers/RecruitingCampaignController.php
  app/Http/Controllers/RecruitingCampaignRecipientController.php
  app/Http/Controllers/RecruitingVisitController.php
  app/Http/Controllers/RsvpController.php
  app/Http/Requests/SendNotificationManualNotificationRequest.php
  app/Http/Requests/StoreNotificationTemplateRequest.php
  app/Http/Requests/StoreRecruitingCampaignRecipientRequest.php
  app/Http/Requests/StoreRecruitingCampaignRequest.php
  app/Http/Requests/StoreRecruitingVisitRequest.php
  app/Http/Requests/UpdateNotificationTemplateRequest.php
  app/Http/Requests/UpdateRecruitingCampaignRecipientRequest.php
  app/Http/Requests/UpdateRecruitingVisitRequest.php
  app/Http/Resources/NotificationTemplate.php
  app/Http/Resources/RecruitingCampaign.php
  app/Http/Resources/RecruitingCampaignRecipient.php
  app/Http/Resources/RecruitingResponse.php
  app/Http/Resources/RecruitingVisit.php
  app/Http/Resources/User.php
  app/Jobs/WeeklyAttendanceEmail.php
  app/Mail/Attendance/Report.php
  app/Mail/DatabaseMailable.php
  app/Mail/GeneralInterestInvite.php
  app/Models/AttendanceExport.php
  app/Models/DuesTransaction.php
  app/Models/NotificationTemplate.php
  app/Models/RecruitingCampaign.php
  app/Models/RecruitingCampaignRecipient.php
  app/Models/RecruitingResponse.php
  app/Models/RecruitingVisit.php
  app/Models/TravelAssignment.php
  app/Models/User.php
  app/Notifications/DatabaseNotification.php
  app/Notifications/GeneralInterestNotification.php
  app/Notifications/WeeklyAttendanceEmailConfirmation.php
  app/Nova/Actions/SendNotification.php
  app/Nova/Actions/SendRecruitingEmail.php
  app/Nova/AttendanceExport.php
  app/Nova/NotificationTemplate.php
  app/Nova/RecruitingVisit.php
  app/Nova/User.php
  app/Policies/AttendanceExportPolicy.php
  app/Policies/NotificationTemplatePolicy.php
  app/Policies/RecruitingVisitPolicy.php
  app/Providers/AuthServiceProvider.php
  database/factories/RecruitingVisitFactory.php
  database/seeders/RecruitingVisitsSeeder.php
  phpstan.neon
  public/js/recruiting/vue.js
  public/js/recruiting/worker.js
  resources/views/attendance/export.blade.php
  resources/views/mail/attendance/report.blade.php
  resources/views/mail/generalinterest/invite.blade.php
  resources/views/recruiting/form.blade.php
  routes/api.php
  routes/web.php
  tests/Feature/ApiAuthTest.php
Labels: area / backend, priority / high, type / technical debt

#2552 Show dues reminders in Nova
  app/Jobs/CreateDuesAreLiveNotificationsInNova.php
  app/Jobs/CreateDuesPaymentDueNotificationInNova.php
  app/Jobs/PruneDuesNotificationsInNova.php
  app/Mail/Dues/RequestComplete.php
  app/Mail/ExpiringPersonalAccessToken.php
  app/Mail/MembershipAgreementSigned.php
  app/Mail/Payment/Confirmation.php
  app/Models/User.php
  app/Notifications/Nova/DuesAreLive.php
  app/Notifications/Nova/DuesPaymentDue.php
  app/Nova/Actions/AddPayment.php
  app/Observers/DuesPackageObserver.php
  app/Observers/DuesTransactionObserver.php
  app/Observers/PaymentObserver.php
  app/Providers/AppServiceProvider.php
  database/migrations/2022_05_30_171006_add_url_and_headers_to_webhook_calls.php
  phpstan.neon
Labels: priority / low, type / feature, area / nova
