Repository RoboJackets/apiary, pull requests merged in 2023-06, with the labels that each got.

#3644 Hide parent/guardian from Nova index
  app/Nova/User.php
Labels: priority / low, type / bug, area / nova

#3682 Sandbox environment setup
  .nomad/apiary.nomad
  .nomad/conf/www.conf
  .nomad/scripts/prestart.sh
  .nomad/scripts/web.sh
  .nomad/var-files/production.hcl
  .nomad/var-files/sandbox.hcl
  .nomad/var-files/test.hcl
  app/Http/Middleware/CASAuthenticate.php
  app/Traits/CreateOrUpdateCASUser.php
  config-validation/cas.php
  config-validation/csp.php
  config-validation/features.php
  config-validation/logging.php
  config-validation/mail.php
  config-validation/passport.php
  config-validation/sentry.php
  config-validation/session.php
  config/features.php
  config/healthcheck.php
  docker-compose.yml
  phpstan.neon
  routes/mailbook.php
Labels: priority / low, type / feature, area / devOps

#3342 Show payments history on user profile page
  .gitignore
  README.md
  app/Http/Controllers/PaymentController.php
  app/Http/Resources/Payment.php
  app/Http/Resources/Travel.php
  app/Http/Resources/TravelAssignment.php
  app/Models/Payment.php
  database/factories/PaymentFactory.php
  database/factories/TravelFactory.php
  database/migrations/2023_02_11_172857_add_international_columns_to_travel.php
  phpcs.xml
  phpstan.neon
  public/img/americanexpress.svg
  public/img/discover.svg
  public/img/mastercard.svg
  public/img/visa.svg
  resources/js/app.js
  resources/js/components/UserEditForm.vue
  resources/js/components/oauth2/OAuth2Authorizations.vue
  resources/js/components/oauth2/PersonalAccessTokens.vue
  resources/js/components/payments/PaymentCardIcon.vue
  resources/js/components/payments/PaymentHistory.vue
  resources/js/components/payments/PaymentMethodDetails.vue
  routes/api.php
  tests/Feature/PaymentTest.php
  tests/Feature/SelfServiceOverrideTest.php
  tests/TestCase.php
Labels: area / frontend, priority / low, type / feature, status / pending changes
