Repository RoboJackets/apiary, pull requests merged in 2024-06, with the labels that each got.

#4637 Don't sync email from CAS/BuzzAPI if it ends with robojackets.org
  app/Jobs/CreateOrUpdateUserFromBuzzAPI.php
  app/Util/CasUser.php
  psalm.xml
Labels: priority / low, type / feature, area / email

#3002 Redirect /nova/login to /login/cas
  routes/web.php
Labels: priority / low, type / enhancement, area / nova, hacktoberfest-accepted

#4185 Changes for RHEL9
  .dockerignore
  .github/workflows/deploy.yml
  .nomad/apiary.nomad
  .nomad/conf/.env.tpl
  .nomad/conf/www.conf
  .nomad/scripts/prestart.sh
  .nomad/scripts/web.sh
  .nomad/var-files/production.hcl
  .nomad/var-files/sandbox.hcl
  .nomad/var-files/test.hcl
  Dockerfile
  config/app.php
  config/cas.php
  config/enlightn.php
  docs/.proselintrc.json
  docs/.styles/config/vocabularies/RoboJackets/accept.txt
  docs/admins/access-overrides.rst
  docs/admins/backup-and-restore.rst
  docs/admins/deployment.rst
  docs/admins/external-services.rst
  docs/index.rst
  docs/officers/dues/data-model.rst
  docs/officers/payments/index.rst
  docs/officers/travel/matrix.rst
Labels: priority / low, type / documentation, area / devOps, status / pending vendor, type / technical debt
