Repository RoboJackets/apiary, pull requests merged in 2024-03, with the labels that each got.

#4456 Update language on travel card
  resources/views/welcome.blade.php
Labels: area / frontend, priority / low, type / enhancement

#4457 Update language on travel tab
  app/Http/Controllers/TravelAssignmentController.php
  app/Jobs/DuesPackageSync.php
  resources/views/travel/index.blade.php
Labels: area / frontend, priority / low, type / enhancement

#4461 CI Generator
  .github/workflows/analysis.yml
  .github/workflows/test.yml
Labels: priority / high, area / devOps, type / technical debt

#4499 Allow $0 trip fees
  app/Http/Controllers/SquareCheckoutController.php
  app/Mail/Travel/TravelAssignmentCreated.php
  app/Models/User.php
  app/Nova/Actions/ReviewTrip.php
  app/Nova/Travel.php
  app/Nova/TravelAssignment.php
  phpstan.neon
  resources/views/mail/travel/assignmentcreated.blade.php
  resources/views/nova/help/travel/feeamount.blade.php
  routes/mailbook.php
Labels: area / backend, priority / critical, type / feature
