Repository RoboJackets/apiary, pull requests merged in 2024-01, with the labels that each got.

#4222 Add Sentry user feedback widget in member UI and Nova
  .gitignore
  app/Nova/Cards/MakeAWish.php
  package-lock.json
  package.json
  resources/js/app.js
  resources/js/components/nova/MakeAWishCard.vue
  resources/js/components/nova/MakeAWishLink.vue
  resources/js/nova.js
  resources/views/layouts/footer.blade.php
  resources/views/vendor/nova/partials/footer.blade.php
  resources/views/vendor/nova/partials/user.blade.php
Labels: area / frontend, priority / low, type / feature

#4201 Swap travel PowerForms for DocuSign API integration
  .dockerignore
  app/Http/Controllers/DocuSignController.php
  app/Jobs/ProcessDocuSignWebhook.php
  app/Jobs/ProcessPostmarkInboundWebhook.php
  app/Jobs/SendDocuSignEnvelopeForTravelAssignment.php
  app/Jobs/SendTravelAssignmentCreatedNotification.php
  app/Models/Travel.php
  app/Models/TravelAssignment.php
  app/Nova/DocuSignEnvelope.php
  app/Observers/DocuSignEnvelopeObserver.php
  app/Observers/TravelAssignmentObserver.php
  app/Providers/NovaServiceProvider.php
  app/Util/DocuSign.php
  config-validation/docusign.php
  config/docusign.php
  docs/admins/permissions-roles.rst
  phpstan.neon
  resources/pdf/direct_bill_airfare_form.pdf
  resources/pdf/travel_information_form.pdf
  routes/web.php
Labels: area / backend, priority / critical, type / feature

#4209 Add support for Matrix itineraries for airfare requests
  .phan/config.php
  app/Http/ContentSecurityPolicy.php
  app/Models/Airport.php
  app/Models/Travel.php
  app/Models/TravelAssignment.php
  app/Nova/Actions/MatrixAirfareSearch.php
  app/Nova/Airport.php
  app/Nova/Travel.php
  app/Nova/TravelAssignment.php
  app/Policies/AirportPolicy.php
  app/Providers/AuthServiceProvider.php
  app/Rules/FareClassPolicyRequiresMarketingCarrierPolicy.php
  app/Rules/MatrixItineraryBusinessPolicy.php
  app/Rules/MatrixItineraryDataStructure.php
  app/Util/Matrix.php
  composer.json
  composer.lock
  config-validation/travelpolicy.php
  config/enlightn.php
  config/scout.php
  config/travelpolicy.php
  database/migrations/2023_12_25_111312_add_matrix_itinerary_to_travel_assignments.php
  database/migrations/2023_12_26_120614_add_airfare_policy_to_travel.php
  database/migrations/2023_12_26_174218_add_update_travel_policy_permission.php
  docs/admins/permissions-roles.rst
  phpcs.xml
  phpstan.neon
  psalm.xml
  resources/views/nova/attendancereportnav.blade.php
  resources/views/nova/matrixadvancedcontrolshelp.blade.php
  resources/views/nova/matrixpolicyhelp.blade.php
  resources/views/travel/matrixitinerarypreview.blade.php
  tests/Feature/PermissionsAndRolesTest.php
Labels: area / backend, priority / critical, type / feature

#4278 Finish DocuSign integration for travel forms
  app/Jobs/ProcessDocuSignWebhook.php
  app/Mail/DocuSign/Travel.php
  app/Models/Airport.php
  app/Models/DocuSignEnvelope.php
  app/Models/Travel.php
  app/Nova/Actions/DownloadDocuSignForms.php
  app/Nova/DocuSignEnvelope.php
  app/Nova/Travel.php
  app/Nova/TravelAssignment.php
  app/Util/DocuSign.php
  app/Util/Matrix.php
  database/migrations/2024_01_12_170913_add_new_financial_fields_to_travel.php
  database/migrations/2024_01_13_162550_add_requested_itinerary_to_docusign_envelopes.php
  phpstan.neon
  resources/pdf/direct_bill_airfare_form.pdf
  resources/pdf/travel_information_form.pdf
  resources/views/mail/docusign/travel/body.blade.php
  resources/views/mail/docusign/travel/subject.blade.php
  resources/views/travel/matrixitineraryprint.blade.php
  routes/mailbook.php
Labels: area / backend, priority / critical, type / feature

#4250 Adding a human readable graduation semester for user profiles in Nova
  app/Http/Requests/UpdateUserRequest.php
  app/Models/User.php
  app/Nova/User.php
Labels: priority / low, type / enhancement, area / nova
