Repository RoboJackets/apiary, pull requests merged in 2024-09, with the labels that each got.

#4786 Added UI for clickup card - Issue #1065
  app/Http/Controllers/DashboardController.php
  resources/views/welcome.blade.php
Labels: area / frontend, priority / low, type / enhancement

#4800 Add Google Form support to RALs
  app/Models/RemoteAttendanceLink.php
  app/Nova/Actions/CreateRemoteAttendanceLink.php
  tests/Unit/RemoteAttendanceLinkTest.php
Labels: priority / medium, area / nova, from / make a wish

#4801 Add shared-device role to allow accounts to bypass authentication checks
  app/Nova/User.php
  app/Util/CasUser.php
  database/migrations/2024_09_08_203808_add_shared_device_role.php
Labels: area / backend, priority / medium, type / feature

#4819 Add data deletion clause to privacy policy
  resources/views/privacy.blade.php
Labels: priority / low, type / documentation, area / mobile

#4834 Fix personal access tokens in Docker Compose
  .nomad/scripts/prestart.sh
  .nomad/scripts/web.sh
  config-validation/passport.php
  docker-compose.yml
Labels: priority / low, area / devOps, type / technical debt
